from zdppy_code import *

print(ResponseSuccess)
print(ResponseSuccessData)
print(ResponseSuccessListData)
print(ResponseParamError)
print(ResponseServerError)
print(ResponseNotFound)
print(ResponseGrpcCanNotUse)
print(ResponseExistsError)
print(ResponseUnAuth)
print(ResponseTokenExpired)
print(ResponseTimeout)
print(ResponseCorsError)
print(ResponseRequestLimitError)
